### Masyvai ir matricos

In [1]:
import numpy as np

In [4]:
sarasas = [4, 7, 11, 6, 9, 69, 420, 777, 31]

In [5]:
masyvas = np.array(sarasas)
print(masyvas, type(masyvas))

[  4   7  11   6   9  69 420 777  31] <class 'numpy.ndarray'>


In [12]:
sugrupuotas = [[4, 7, 11], [6, 9, 69], [420, 777, 31]]

In [13]:
matrica = np.array(sugrupuotas)
print(matrica)

[[  4   7  11]
 [  6   9  69]
 [420 777  31]]


In [15]:
imtis = np.arange(8, 30, 3)
print(imtis, type(imtis))

[ 8 11 14 17 20 23 26 29] <class 'numpy.ndarray'>


In [16]:
nuliai = np.zeros(10)
print(nuliai)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
nuliai_6x6 = np.zeros((6, 6))
nuliai_6x6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
akis = np.eye(6)
akis

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
akis[0][1] = 3
akis[1][0] = 2

In [22]:
akis

array([[1., 3., 0., 0., 0., 0.],
       [2., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [27]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [28]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

### Random arrays

In [29]:
np.random.rand(10)

array([0.09716288, 0.63866266, 0.20209719, 0.43181477, 0.12863134,
       0.36812085, 0.34458931, 0.01488635, 0.93703929, 0.89751861])

In [30]:
np.random.rand(5, 5)

array([[0.29049641, 0.98730751, 0.97501148, 0.65451445, 0.63093389],
       [0.26342077, 0.63964653, 0.11017875, 0.46178912, 0.53139601],
       [0.69621914, 0.88098023, 0.78353471, 0.81383135, 0.92758863],
       [0.13313635, 0.50257899, 0.29631714, 0.19943429, 0.80410446],
       [0.39741363, 0.46537981, 0.07123037, 0.48898799, 0.19585027]])

In [32]:
np.random.randn(5, 5) * 100

array([[ -23.10517783,  -66.48133081,   99.55430324,  -85.1354204 ,
         -67.99655227],
       [  12.75649489,   94.5498255 ,  -33.31916065,  120.57169027,
         -98.79923708],
       [ -63.07865817,  -68.40287637,  -23.13270506,   12.40539869,
        -148.74100362],
       [  84.8035021 ,  -32.53176196,  -17.81130852, -133.66482807,
         -66.06075784],
       [  23.99401179,  115.74288033,  -32.35840564, -130.13828935,
         143.63985946]])

In [33]:
np.random.randint(100, 200, 10)

array([164, 174, 140, 177, 190, 114, 102, 166, 124, 189])

### Masyvu pertvarka

In [34]:
betko_64 = np.random.randint(100, 999, 64)
betko_64

array([541, 929, 314, 997, 843, 321, 961, 624, 948, 303, 450, 880, 913,
       603, 661, 854, 951, 252, 755, 618, 441, 781, 240, 881, 438, 371,
       507, 469, 987, 680, 992, 682, 922, 677, 723, 529, 102, 252, 906,
       479, 550, 362, 668, 701, 319, 827, 507, 278, 133, 405, 307, 608,
       298, 702, 459, 228, 942, 363, 750, 287, 159, 139, 822, 927])

In [35]:
betko_8x8 = betko_64.reshape(8, 8)
betko_8x8

array([[541, 929, 314, 997, 843, 321, 961, 624],
       [948, 303, 450, 880, 913, 603, 661, 854],
       [951, 252, 755, 618, 441, 781, 240, 881],
       [438, 371, 507, 469, 987, 680, 992, 682],
       [922, 677, 723, 529, 102, 252, 906, 479],
       [550, 362, 668, 701, 319, 827, 507, 278],
       [133, 405, 307, 608, 298, 702, 459, 228],
       [942, 363, 750, 287, 159, 139, 822, 927]])

In [36]:
betko_20 = np.random.randint(100, 999, 20)
betko_4x5 = betko_20.reshape(4, 5)
print(betko_4x5)

[[612 347 709 477 810]
 [780 317 227 476 240]
 [890 970 196 566 539]
 [319 802 873 282 950]]


### naudingi metodai

In [38]:
print(min(betko_64))
print(betko_64.min())

102
102


In [39]:
betko_8x8.max()

997

In [47]:
print(betko_20.argmin(), betko_20.min())

12 196


In [48]:
betko_8x8.argmax()

3

In [42]:
kvadratas = np.zeros((5, 5)).astype(int) + 1
print(kvadratas)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [46]:
kubas = np.zeros((5, 5, 5)).astype(int) + 1
print(kubas)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [43]:
betko_8x8.shape

(8, 8)

In [44]:
betko_20.shape

(20,)

In [45]:
betko_4x5.dtype

dtype('int32')

### indeksacija ir reiksmiu traukimas

In [49]:
betko_20

array([612, 347, 709, 477, 810, 780, 317, 227, 476, 240, 890, 970, 196,
       566, 539, 319, 802, 873, 282, 950])

In [50]:
betko_20[2:5]

array([709, 477, 810])

In [51]:
betko_20[::2]

array([612, 709, 810, 317, 476, 890, 196, 539, 802, 282])

In [53]:
betko_20[-5] = 777
betko_20

array([612, 347, 709, 477, 810, 780, 317, 227, 476, 240, 890, 970, 196,
       566, 539, 777, 802, 873, 282, 950])

In [55]:
betko_8x8

array([[541, 929, 314, 997, 843, 321, 961, 624],
       [948, 303, 450, 880, 913, 603, 661, 854],
       [951, 252, 755, 618, 441, 781, 240, 881],
       [438, 371, 507, 469, 987, 680, 992, 682],
       [922, 677, 723, 529, 102, 252, 906, 479],
       [550, 362, 668, 701, 319, 827, 507, 278],
       [133, 405, 307, 608, 298, 702, 459, 228],
       [942, 363, 750, 287, 159, 139, 822, 927]])

In [57]:
betko_8x8[2,2:5]

array([755, 618, 441])

In [58]:
betko_8x8[2:-2, 2:-2]

array([[755, 618, 441, 781],
       [507, 469, 987, 680],
       [723, 529, 102, 252],
       [668, 701, 319, 827]])

In [60]:
betko_8x8[-3:, -3:]

array([[827, 507, 278],
       [702, 459, 228],
       [139, 822, 927]])

In [61]:
betko_4x5[-3:, -3:]

array([[227, 476, 240],
       [196, 566, 539],
       [873, 282, 950]])

### traukimas pagal salyga

In [63]:
tiesa_8x8 = betko_8x8 > 500
tiesa_8x8

array([[ True,  True, False,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False,  True, False,  True],
       [False, False,  True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False],
       [ True, False,  True,  True, False,  True,  True, False],
       [False, False, False,  True, False,  True, False, False],
       [ True, False,  True, False, False, False,  True,  True]])

In [66]:
dideli = betko_8x8[tiesa_8x8]

In [65]:
betko_8x8[betko_8x8 < 200]

array([102, 133, 159, 139])

In [70]:
dideli.shape

(38,)

In [69]:
dideli.reshape(19, 2)

array([[541, 929],
       [997, 843],
       [961, 624],
       [948, 880],
       [913, 603],
       [661, 854],
       [951, 755],
       [618, 781],
       [881, 507],
       [987, 680],
       [992, 682],
       [922, 677],
       [723, 529],
       [906, 550],
       [668, 701],
       [827, 507],
       [608, 702],
       [942, 750],
       [822, 927]])

### elgsenos ypatumai

In [92]:
betko_20

array([612, 347, 709, 477, 810, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 802, 873, 282, 950])

In [88]:
ispjova = betko_20[5:-5]
ispjova

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [77]:
ispjova[:] = 999

In [78]:
betko_20

array([612, 347, 709, 477, 810, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 802, 873, 282, 950])

In [83]:
kopija = betko_20.copy()
kopija

array([612, 347, 709, 477, 810, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 802, 873, 282, 950])

In [84]:
kopija == betko_20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [89]:
kopijos_ispjova = kopija[5:-5]
kopijos_ispjova

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [93]:
kopijos_ispjova = np.random.randint(100, 999, 10)

In [95]:
kopija

array([612, 347, 709, 477, 810, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 802, 873, 282, 950])

### Matematines operacijos

In [96]:
pirmi_10 = np.random.randint(0, 99, 10)
antri_10 = np.random.randint(0, 99, 10)
print(pirmi_10, antri_10)

[45 31 92 91  2 33 59 33 58 83] [81 51 60 40 30 16 71 71 75 67]


In [97]:
sudetis = pirmi_10 + antri_10
sudetis

array([126,  82, 152, 131,  32,  49, 130, 104, 133, 150])

In [98]:
daugyba = pirmi_10 * antri_10
daugyba

array([3645, 1581, 5520, 3640,   60,  528, 4189, 2343, 4350, 5561])

In [99]:
dalyba = antri_10 / pirmi_10
dalyba

array([ 1.8       ,  1.64516129,  0.65217391,  0.43956044, 15.        ,
        0.48484848,  1.20338983,  2.15151515,  1.29310345,  0.80722892])

In [102]:
kubu = pirmi_10 ** 10
kubu

array([ -655691255, -1796951359,  1158676480,   270703673,        1024,
       -2057521855, -1489217927, -2057521855,  -939809792, -1816383223],
      dtype=int32)

In [103]:
np.sin(pirmi_10)

array([ 0.85090352, -0.40403765, -0.77946607,  0.10598751,  0.90929743,
        0.99991186,  0.63673801,  0.99991186,  0.99287265,  0.96836446])

In [104]:
np.log(pirmi_10)

array([3.80666249, 3.4339872 , 4.52178858, 4.51085951, 0.69314718,
       3.49650756, 4.07753744, 3.49650756, 4.06044301, 4.41884061])